In [1]:
import torch
inputs = torch.tensor(
[[0.43, 0.15, 0.89],
 [0.55, 0.87, 0.66],
 [0.57, 0.85, 0.64],
 [0.22, 0.58, 0.33],
 [0.77, 0.25, 0.10],
 [0.05, 0.80, 0.55]]
)

In [5]:
query = inputs[1]

attn_scores_2 = torch.empty(inputs.shape[0])
print(attn_scores_2, inputs.shape)
for i, x_i in enumerate(inputs):
    print(x_i, query)
    attn_scores_2[i] = torch.dot(x_i, query)

print(attn_scores_2)

tensor([0.0000e+00, 0.0000e+00, 1.0500e-08, 2.7177e-06, 8.5758e-07, 8.3092e+20]) torch.Size([6, 3])
tensor([0.4300, 0.1500, 0.8900]) tensor([0.5500, 0.8700, 0.6600])
tensor([0.5500, 0.8700, 0.6600]) tensor([0.5500, 0.8700, 0.6600])
tensor([0.5700, 0.8500, 0.6400]) tensor([0.5500, 0.8700, 0.6600])
tensor([0.2200, 0.5800, 0.3300]) tensor([0.5500, 0.8700, 0.6600])
tensor([0.7700, 0.2500, 0.1000]) tensor([0.5500, 0.8700, 0.6600])
tensor([0.0500, 0.8000, 0.5500]) tensor([0.5500, 0.8700, 0.6600])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [6]:
res = 0
for idx, element in enumerate(inputs[0]):
    res += inputs[0][idx] * query[idx]

print(res)
print(torch.dot(inputs[0], query))

tensor(0.9544)
tensor(0.9544)
